package com.cobo.wallet.infras.dao.mapper;

import com.cobo.wallet.infras.dao.entity.AccountOptFlowDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AccountOptFlowDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    int insert(AccountOptFlowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    int insertSelective(AccountOptFlowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    AccountOptFlowDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    int updateByPrimaryKeySelective(AccountOptFlowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_opt_flow
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    int updateByPrimaryKey(AccountOptFlowDO record);

    List<AccountOptFlowDO> selectByUserIdAndCurrency(@Param("userId") String userId, @Param("currency") String currency);
}