package com.cobo.wallet.infras.dao.mapper;

import com.cobo.wallet.infras.dao.entity.UserAccountDO;
import org.apache.ibatis.annotations.Param;

public interface UserAccountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    int insert(UserAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    int insertSelective(UserAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    UserAccountDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    int updateByPrimaryKeySelective(UserAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated Fri Aug 09 22:55:58 CST 2024
     */
    int updateByPrimaryKey(UserAccountDO record);

    UserAccountDO selectByUserId(@Param("userId") String userId, @Param("currency") String currency);

    UserAccountDO lockByUserIdNoWait(@Param("userId") String userId, @Param("currency") String currency);
}